### ISSUE TITLE
Hiding "More Videos" tab in embedded players.

### ISSUE THREAD

**Issue by akashchgupta** [lawrencehook/remove-youtube-suggestions#30] opened 2021-08-25 10:50 UTC
Really love your chrome extension. But I was looking for an extension which disables "More Videos" suggestion tab too. Your chrome webstore page has an image which shows that feature under "Near end-of-video embedded overlays" section. But I could not find it in the latest extension itself. Please provide a fix.

**Comment by remi-garcia** [comment] 2021-08-25 13:35
Duplicate of #24

**Comment by lawrencehook** [comment] 2022-02-12 21:26
If this issue is about suggestions in embedded videos, I believe should be fixed as of de72e29c65aefead79cb22a48dd0a1f6b5bcc920

But please let me know if not, thanks

**Comment by lawrencehook** [comment] 2022-04-05 23:18
Ah I'm seeing the "more videos" element now.

`div.ytp-pause-overlay`

**Comment by lawrencehook** [comment] 2022-04-08 05:09
Should be fixed as of ca78ed5a1028b9b178976a6e65e6734049d05319

**Closed by lawrencehook** 2022-04-08 05:09 UTC
